#!/usr/bin/env python3
"""Produce the GNOME 42 module format from the shared modern panel source."""
from pathlib import Path
import json
repo = Path(__file__).resolve().parents[1]
source = repo / 'extension'
target = repo / 'extension-legacy'
target.mkdir(exist_ok=True)
text = (source / 'extension.js').read_text()
start = text.index('const Indicator =')
end = text.index('export default class AsusControlExtension')
body = text[start:end]
body = body.replace("new MessageTray.Source({title: 'ASUS Control Center', iconName: 'preferences-system-symbolic'})", "new MessageTray.Source('ASUS Control Center', 'preferences-system-symbolic')")
body = body.replace("this._source.addNotification(new MessageTray.Notification({source: this._source, title, body, iconName: icon, isTransient: true}));", "const notification = new MessageTray.Notification(this._source, title, body, {gicon: new Gio.ThemedIcon({name: icon})});\n        notification.setTransient(true);\n        this._source.showNotification(notification);")
header = '''// SPDX-License-Identifier: MPL-2.0
// Generated by scripts/generate-legacy-panel.py; edit extension/ instead.
const {Clutter, Gio, GLib, GObject, St} = imports.gi;
const Main = imports.ui.main;
const PanelMenu = imports.ui.panelMenu;
const PopupMenu = imports.ui.popupMenu;
const MessageTray = imports.ui.messageTray;
const Me = imports.misc.extensionUtils.getCurrentExtension();
const {PROFILES, profileIndex, reducePower} = Me.imports.profiles;
const {readText, powerState, batteryPercent} = Me.imports.platform;
'''
footer = '''function init() {
    return {
        enable() {
            this._indicator = new Indicator(Me.path);
            Main.panel.addToStatusArea(Me.metadata.uuid, this._indicator);
        },
        disable() {
            this._indicator?.destroy();
            this._indicator = null;
        },
    };
}
'''
(target / 'extension.js').write_text(header + body + footer)
for name in ('profiles.js', 'platform.js'):
    code = (source / name).read_text()
    code = code.replace("import Gio from 'gi://Gio';", 'const Gio = imports.gi.Gio;')
    code = code.replace('export const ', 'var ').replace('export function ', 'function ')
    (target / name).write_text(code)
metadata = json.loads((source / 'metadata.json').read_text())
metadata['shell-version'] = ['42']
(target / 'metadata.json').write_text(json.dumps(metadata, indent=2) + '\n')
for name in ('stylesheet.css', 'telemetry.py', 'lighting.py'):
    (target / name).write_bytes((source / name).read_bytes())
